### ISSUE TITLE
Cannot find d3.geomap.css.map

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#104]
http://localhost:8888/wordpresstest/wp-content/plugins/snowball/lib/d3-geomap/css/d3.geomap.css.map
It still seems to work but an error message says it is missing the file.

**Comment by thomaspark** [comment]
Can you post a screenshot and what url you're getting this error on?

Source map files help you to read minified css/js files in dev tools, but I'm not getting this error.

**Comment by brianlee389** [comment]
<img width="560" alt="screen shot 2015-07-07 at 2 39 04 pm" src="https://cloud.githubusercontent.com/assets/6540823/8554136/fc822892-24b5-11e5-8da9-e6f607cb3399.png">
This error happens when I open a choropleth block.

**Comment by thomaspark** [comment]
By any chance did you minify `geomap.css`? Are you getting this error on main branch or just your gulp branch?

**Comment by brianlee389** [comment]
I haven't minified the new libraries you just added and I'm getting them in master and in mine as well.

**Comment by thomaspark** [comment]
Does removing this line in `d3.geomap.css` get rid the message?

`/*# sourceMappingURL=geomap.css.map*/`

**Comment by brianlee389** [comment]
Yes it does

**Comment by thomaspark** [comment]
Still don't know why I don't get that error message, but I'll remove the line since a source map file isn't provided.

**Comment by brianlee389** [comment]
I don't have the actual geomap.css.map file. Is it possible that you may have it, but not committed it?

**Comment by thomaspark** [comment]
No I don't, the library doesn't include a source map file.
