### ISSUE TITLE
Splash Block Issues

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#110]

**Comment by brianlee389** [comment]
Images don't seem to fit well in the splash block.
If two splash blocks are in 1 article, the latter one takes the place of the first one and where the picture should be for the latter one doesn't exist.

**Comment by thomaspark** [comment]
Turns out you had a stray period in the custom CSS of Splash 1, which caused the next ruleset (Splash 2) to have the wrong selector.

<img width="641" alt="screen shot 2015-07-20 at 9 01 47 pm" src="https://cloud.githubusercontent.com/assets/900407/8791006/bf78775e-2f22-11e5-809d-0cfd9a88ae52.png">
