### ISSUE TITLE
Add to WP plugins

### ISSUE THREAD

**Issue by xmatthewx** [thomaspark/snowball#121]
Is this available via Wordpress plugins installer? If so, you might add a link to your readme. If not, consider it. It would make it much easier for others to help with your tests and feedback. 

Awesome work!

**Comment by sukritchhabra** [comment]
https://help.github.com/articles/support-for-subversion-clients/

**Comment by thomaspark** [comment]
Finally added to the WordPress.org directory. :smiley:
https://wordpress.org/plugins/snowball/

We welcome all feedback!
