### ISSUE TITLE
All Permalinks may not work

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#128]

**Comment by brianlee389** [comment]
<img width="843" alt="screen shot 2015-08-24 at 12 02 36 pm" src="https://cloud.githubusercontent.com/assets/6540823/9445048/1842fc74-4a58-11e5-883f-80e261fcdffa.png">
Permalink cannot be changed. If you change it, it will redirect to the link specified, but the site you are looking for will not be there. Also when you save it, it goes back to its old name.

**Comment by brianlee389** [comment]
I'm not sure if this is an issue, but changing the permalink type will not affect the snowball article. Changing one does nothing, snowball articles will always have the same link.

**Comment by thomaspark** [comment]
I opened a new ticket for your second issue.

For not being able to change permalink slugs, I think I've tracked it down to this line in `snowball-config.php`:

```
remove_meta_box('slugdiv', 'snowball', 'normal'); // Slug
```

It seems like we need to keep `slugdiv` in order for it to work. Can you test on your end and confirm?

One solution is to just remove this line. But then we have an extra metabox and screen option. So a better solution might be to add the slugdiv metabox code to `snowball-settings.php` and set visibility to hidden. Haven't tested this yet to see if it will work.

**Comment by brianlee389** [comment]
Okay I will try this out.

**Comment by thomaspark** [comment]
Fixed in #163.
