### ISSUE TITLE
Content blocks aren't populating when there is an article saved and populates when view article is clicked

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#132]
August 6th, 2015 - couldn't recreate this error, but using the article:
"try it with a title" by demo in snowball.openhtml.org/wp-admin. 
The article in the admin view doesn't show it's block, but blocks are shown in the view article.

**Comment by thomaspark** [comment]
Cannot replicate. Probably has to do with old post created with different schema.
