### ISSUE TITLE
Updating table in handsontable doesn't update the html in modal

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#137]

**Comment by sukritchhabra** [comment]
- Doesn't work with delete.
- Pressing the delete key to completely delete the contents of the cell doesn't update the table
- Also, removing columns/rows leaves empty `<td></td>` tags. If multiple additions and deletions take place there remain a lot of empty tags.

**Comment by thomaspark** [comment]
Fixed in dd44b8e3de55a2bee608acfbd3b238a8346d7714.
