### ISSUE TITLE
Testing Plugin compatibility

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#139]
- [ ] Advanced Custom Fields (custom field creator to add additional meta to posts (we take heavy advantage of this on Magazine style articles)
- [x] Allow Multiple Accounts (we use this to tie user accounts to a single departmental email address). 
- [x] Bad Behavior (for spam). 
- [ ] Better Art Direction (to inject any additional stylesheets/scripts onto the page). 
- [ ] Clean Up Images (for housekeeping). 
- [ ] CloudFlare. 
- [x] Co-Authors Plus (for multi-authorship). 
- [x] Contact Form 7 (contact form). 
- [ ] Disqus Comment System (comments!). 
- [x] Enable Media Replace (replace photos). 
- [x] Hello Dolly. 
- [x] Jetpack. 
- [ ] Liveblog (for liveblogging). 
- [x] Lockdown WP Admin (changes the admin URL). 
- [x] Members (edit user roles, capabilities, plus add new ones). 
- [x] Really Simple CAPTCHA (for CF7). 
- [x] Regenerate Thumbnails (to flush thumbnails after new ones are added). 
- [x] Simple Ads Manager (for ads). 
- [x] Simple Custom Post Order (post ordering). 
- [x] Simple Local Avatars (local profile pics). 
- [x] Term Management Tools (move posts in bulk between cats). 
- [x] Thumbnail Crop Position (change the crop position). 
- [ ] Toggle wpautop (for the magazine articles). 
- [ ] TriFunctions (in-house functions include). 
- [x] User Switching (convenience). 
- [x] WordPress Importer. 
- [x] WP-Mail-SMTP (lets us self-sign notification emails via Gmail routing). 
- [x] WP-Polls (for polls). 
- [x] WP Password Generator (for all our writer accounts— we don't give writers access to our system, but we create a new user for every single one. I have a question on this below). 
- [x] WP Subtitle (for decks). 
  Yoast SEO (SEO).

**Comment by thomaspark** [comment]
Test environment set up at http://test.openhtml.org/wp-admin/.

**Comment by sukritchhabra** [comment]
* Advanced Custom Fields: unclear which one they're using
* Bad Behaviour: not found

**Comment by sukritchhabra** [comment]
##Problems

**Comment by sukritchhabra** [comment]
* Cleanup Images: Used an image as a splash image. Cleanup didn't count it as being used, and upon deletion removed the image from the media library.

**Comment by sukritchhabra** [comment]
# Urgent
- `Cleanup Images`: Used an image as a splash image. Cleanup didn't count it as being used, and upon deletion removed the image from the media library.
- `CloudFlare` had a section in their signup which said updated nameservers and since it was getting records for openhtml.org, I was little skeptical about going through with that.
- `Toggle wpautop`: Doesn't work. Ideally, enabling this option would not cause line breaks on a `double Enter` but I think it doesn't work with our text block.

**Comment by sukritchhabra** [comment]
## Not built to handle Snowball
- `Better Art Direction`: The option is being added to the posts and pages but not to snowball.
- `Co-Authors Plus`: Doesn't break anything, but adding more than one author doesn't add it to the `[author]` tag. The `[author]` tag still take only the first from all the authors added. Also authors usually adds their section to the bottom of the editor, but with Snowball it is added above the editor.
- `Disqus Comments` are also not being added to Snowball but is being added to pages and posts
- `Liveblogging` is also not being added to Snowball but is being added to posts
- `TriFunctions`: Couldn't find plugin, neither  in the wordpress search nor a web search

**Comment by sukritchhabra** [comment]
## Warnings
- `Advanced Custom Fields`: unclear which one they're using
- `Better Art Direction`: (there were two, used the newer one for testing)
- What features of `Jetpack` are activated?
- Couldn't find the use of `Really Simple CAPTCHA`. No control panel and doesn't apear in either Snowball and or pages/post editor menu.
- `WordPress Importer` is not set to import to Snowball.
- Selecting Upload option in `Simple Ads Manager` doesn't do anything. (Images might need to be the exact same size as set in the Ads Place Size section)

**Comment by sukritchhabra** [comment]
Check #158 and #157
