### ISSUE TITLE
There's a flash of all the tables on the page and the table of contents together on load.

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#140]
- Also exists on the Mac on chrome but doesn't happen in firefox

![handsontableloadprob](https://cloud.githubusercontent.com/assets/6703126/9205457/50ae9294-4030-11e5-8cc0-e281bb78b5f1.png)

**Comment by thomaspark** [comment]
This is probably caused by Scoper.

One way to mitigate it is to use less custom CSS. If we had global CSS, that would help too.
