### ISSUE TITLE
Lighbox Bug

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#141]
- Parts of the preview are being added to the border

![lightboxerror1](https://cloud.githubusercontent.com/assets/6703126/9205956/1906951e-4033-11e5-9b49-4d9fcdeaee3e.png)
![lightboxerror2](https://cloud.githubusercontent.com/assets/6703126/9205957/191d8f58-4033-11e5-9c3b-8c6fef9d9522.png)

**Comment by thomaspark** [comment]
Looks like an upstream bug with FluidBox. The background-image is repeating on the edges.

You should open an issue at https://github.com/terrymun/Fluidbox and suggest setting `.fluidbox-ghost` to `background-repeat: no-repeat`.

While we wait for it to be fixed, we can apply that style to our own page, or set a border color with full opacity.

**Comment by sukritchhabra** [comment]
- Posted issue at https://github.com/terrymun/Fluidbox/issues/131
- Fixed on our Docs page
