### ISSUE TITLE
Changing names of classes to prevent style clashes

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#144]

**Comment by thomaspark** [comment]
@brianlee389, are there any open clashes or can this be closed?

**Comment by brianlee389** [comment]
There is one clash with text color of the splash block.

**Comment by thomaspark** [comment]
Can you give more details about where this clash happens? What theme? Can you post a screenshot?

**Comment by brianlee389** [comment]
I found that Wordpress Twenty Fifteen causes some css clashing issues.

**Comment by brianlee389** [comment]
Also Wordpress Twenty Thirteen and Fourteen themes style gets messed up with the plugin.

**Comment by thomaspark** [comment]
You should document all of the themes you tested, including the ones that are compatible.

For the ones that have problems, it would be helpful to add more detailed comments and screenshots that show some of problems rather than being vague.
