### ISSUE TITLE
On the snowball.openhtml.org front-page, there is an unnecessary form  below our form.

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#153]
- The form is not apart of our plugin and is not present on the admin page but is present on the front page

**Comment by thomaspark** [comment]
This is WordPress's native commenting feature, which you can toggle here:

<img width="324" alt="screen shot 2015-08-22 at 1 03 10 pm" src="https://cloud.githubusercontent.com/assets/900407/9424970/3180e218-48ce-11e5-83b4-841e7be27665.png">

We should make sure `snowball.css` gives `#comments` some decent styling.
