### ISSUE TITLE
Permalink settings not used

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#154]
Snowball doesn't follow the Settings > Permalink Settings value. Only "Default" and "Post name" have an effect.

<img width="881" alt="screen shot 2015-08-24 at 1 55 37 pm" src="https://cloud.githubusercontent.com/assets/900407/9447934/d247d4d2-4a67-11e5-9692-de8884182022.png">

**Comment by brianlee389** [comment]
I just tested this again and all of them work except for "Day and name" and "Month and name". Those 2 default to using the Post name option.

**Comment by thomaspark** [comment]
it seems custom post types aren't really meant to take the permalink settings and don't support year/month/date. Like a custom slug, this might be supported by a third-party plugin.

**Comment by brianlee389** [comment]
http://wordpress.stackexchange.com/questions/83797/custom-post-type-yearly-monthly-archive-permalinks
This is a possible way to set permalinks based on dates, if we still want that.
