### ISSUE TITLE
Add option for custom post type's permalink slug

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#162]
Instead of using `/snowball/article`, allow users to set a custom slug in Settings.

**Comment by brianlee389** [comment]
Links related to the issue
- http://wordpress.stackexchange.com/questions/41988/redeclare-change-slug-of-a-plugins-custom-post-type

**Comment by brianlee389** [comment]
I think using Custom Structure Permalink will allow you to change this.

**Comment by brianlee389** [comment]
This can be fixed by using the plugin: 
[Custom Permalinks](https://wordpress.org/plugins/custom-permalinks)
