### ISSUE TITLE
Snowball Admin Page, side menu

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#167]
In Chrome and Firefox,
when you put the mouse on the left side of the webpage when scrolled to the bottom of the page, the left nav menu bar becomes small and does not fit the height.
Before:
<img width="701" alt="screen shot 2015-08-28 at 10 30 54 am" src="https://cloud.githubusercontent.com/assets/6540823/9548694/f2f794f0-4d6f-11e5-8fe9-f5c3b0380d7e.png">
After:
<img width="729" alt="screen shot 2015-08-28 at 10 31 10 am" src="https://cloud.githubusercontent.com/assets/6540823/9548696/f3f71d94-4d6f-11e5-9c74-a1244ea83124.png">

**Comment by brianlee389** [comment]
I can't recreate this issue anymore, but look out for it.

**Comment by thomaspark** [comment]
Removing hover functionality. The less we mess with WP's interface, the better. For more screen space, users can collapse admin menu.
