### ISSUE TITLE
IE9 & IE10 Issues

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#169]
- Text doesn't show in the splash blocks for IE9 & 10. 
  - When I checked the dev tools, it underline some css properties with red squiggly lines. 
  - Also found this: http://stackoverflow.com/questions/17695865/why-does-display-ms-flex-ms-justify-content-center-not-work-in-ie10

**Comment by thomaspark** [comment]
Which css properties get red squiggly lines? Can you submit a patch that makes it more compatible with IE10?

**Comment by sukritchhabra** [comment]
- Soundcloud doesn't support IE9 and therefore their widget isn't working: http://help.soundcloud.com/customer/portal/articles/1331463-why-is-my-widget-not-showing-up-in-internet-explorer-
- `.columns` in the Columns block is not getting the property `flex: 1;`. Also the wrapping `.row` is not getting the property `display: flex;`

**Comment by brianlee389** [comment]
![squig](https://cloud.githubusercontent.com/assets/6540823/9688997/ca3bb438-5300-11e5-8914-877635de53eb.png)
The lines are on:
-ms-justify-content: center;
-ms-align-items: center;

**Comment by brianlee389** [comment]
Also I'm leaving now, shoot me an email if you want me to test anything with IE9 or 10. Have a good weekend!!

**Comment by thomaspark** [comment]
Splash block issue fixed in #170.
