### ISSUE TITLE
Generic function (and/or define) names

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#178]
Response from WP.org:

> Generic function (and/or define) names
> 
> All plugins should have unique function names, defines, and classnames. This will prevent your plugin from conflicting with other plugins or themes.
> 
> For example, if your plugin is called "Easy Custom Post Types", then you might prefix your functions with ecpt_{your function name here}. Similarly a define of LICENSE would be better done as ECPT_LICENSE. You can use namespaces instead, however make sure that those also are unique. A namespace or class of 'MyPlugin' is NOT actually all that unique, you see.
> 
> Please update your plugin to use more unique names.
> 
> Examples:
> 
> `add_blocks_callback()`
> `add_article_callback()`
> 
> All your functions have to be unique.

**Comment by brianlee389** [comment]
Would appending "snowball_" to the beginning of the function names be good enough?

**Comment by thomaspark** [comment]
Yep, that should be enough for these two. But we should also check if there
are any other functions or globals that need to be prefixed.

**Comment by brianlee389** [comment]
Okay I'm going to see if any other generic functions exist and append that

**Comment by thomaspark** [comment]
Fixed in #179.
