### ISSUE TITLE
WordPress Preview doesn't autoupdate

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#193]
- Clicking preview button loads preview. But if you edit after that and then click preview, changes are not reflected in preview tab.
- The tab needs to be closed and preview needs to be clicked again to see the update.
- There is a workaround: Use `View Article` instead but still should be fixed.
- Probably a wordpress issue.

**Comment by thomaspark** [comment]
Clicking preview button currently updates the preview. However, simply reloading the preview tab doesn't update, but this is the normal behavior with post as well.
