### ISSUE TITLE
Last paragraph in text module not being parsed as a paragraph

### ISSUE THREAD

**Issue by noelforte** [thomaspark/snowball#212]
In all of my text modules, the last paragraph is being converted to plain text, but is not being wrapped in `<p>` tags.

**Comment by thomaspark** [comment]
Nice catch! Fixed this issue, as well as interpreting line breaks as `<br>` tags, and making the code format nicely. Will be included in the next release.

<img width="1360" alt="screen shot 2015-11-14 at 4 13 02 pm" src="https://cloud.githubusercontent.com/assets/900407/11165864/c6b6bf02-8aea-11e5-886e-56d33652372f.png">
