### ISSUE TITLE
Could not insert image from media library

### ISSUE THREAD

**Issue by kasynych** [thomaspark/snowball#213]
Had to insert image URL manually

**Comment by thomaspark** [comment]
The image URL can be inserted by clicking the "Choose Image" button:

<img width="577" alt="screen shot 2015-11-06 at 1 25 56 am" src="https://cloud.githubusercontent.com/assets/900407/10986837/679540aa-8425-11e5-9b96-5306b1b511fc.png">

...selecting an image from "Media Library", then clicking the "Insert into post" button.

<img width="293" alt="screen shot 2015-11-06 at 1 26 07 am" src="https://cloud.githubusercontent.com/assets/900407/10986846/6b686108-8425-11e5-9af1-6e2ca28ad027.png">

If that's not working for you, please let me know, along with your browser info.
