### ISSUE TITLE
Call to a member function add_cap() on a non-object

### ISSUE THREAD

**Issue by noelforte** [thomaspark/snowball#220]
Hey guys, thanks for implementing the #219. Unfortunately, the plugin is now crashing the entire backend due to a fatal error.

```
PHP Fatal error:  Call to a member function add_cap() on a non-object in /home/tadmin/public_html/wp-content/plugins/snowball/inc/snowball-config.php on line 68
```

Hope a fix can be deployed soon.

**Comment by thomaspark** [comment]
Thanks for the speedy pull request (#221). The bug fix has been pushed with v0.4.3.
