### ISSUE TITLE
Snowball not work image slider in my Newspaper 7 theme

### ISSUE THREAD

**Issue by yerbol89** [thomaspark/snowball#225]
I install Snowball plugin my site. Its cool plugin. Nice work.
1:
My site defoult theme Newspaper 7 not work Image Slider. Use Snowpall theme slider work normal.
How i fix?
https://szh.kz/snowball/7020/
End 800*350 its image slider. But image slider not work my theme. Please help me.
1. Please add use image slider. Example:
   https://vlast.kz/gorod/18022-rekonstrukcia-centralnogo-stadiona-almaty-pocemu-ee-nelza-delat.html
   This site use images stadion image slider.

sorry my bad english. i use google translate.

**Comment by thomaspark** [comment]
Unfortunately Newspaper 7 is a paid theme so I'm not able to test it for myself.

The link you provided is not working anymore. If you provide a link to a live example of the image slider, I'll try to figure out a fix. Thanks.

**Comment by yerbol89** [comment]
Use snowball theme work nice.
https://szh.kz/snowball/test2/

After use my theme image slider not work.
https://szh.kz/snowball/test1/

Thanks create this plugin. Today i first create post. Its really cool plugin. I like it. :)
https://szh.kz/snowball/tesla-elektrokarymen-almatydan-parizhge/

**Comment by thomaspark** [comment]
It looks like some of the CSS for the image slider is getting jumbled. I believe this is due to WP Super Minify plugin. Could you try disabling that plugin, clear your cache, and see if the problem goes away?

**Comment by yerbol89** [comment]
@thomaspark thanks. 
After i disable WP Super Minify plugin image slider work.

**Comment by thomaspark** [comment]
Glad it's working properly now. I also noticed a height bug on your theme:

<img width="754" alt="screen shot 2016-06-24 at 4 24 06 pm" src="https://cloud.githubusercontent.com/assets/900407/16349678/1f3ed3f2-3a28-11e6-9683-87a4988d4cec.png">

I will push an update that fixes this soon.
