### ISSUE TITLE
Visual Compressor dont show snowball post?

### ISSUE THREAD

**Issue by yerbol89** [thomaspark/snowball#230]
A many site pay Newspaper wordpress theme. And i use my site Newspaper theme.
http://themeforest.net/item/newspaper/5489609

I have a problem. I select category post and publish. But шт home page not show snowball post. Post show after open category. Home page select category not show snowball post.

Newspaper use Visual Compressor plugin.

**Comment by thomaspark** [comment]
Snowball posts should show up in categories as expected. Unfortunately it's tricky to troubleshoot this issue since we don't have access to the paid theme. If you have a link to the site, that would be helpful.

**Comment by yerbol89** [comment]
@thomaspark i send you email files. hello@thomaspark.co
Thanks.

**Comment by thomaspark** [comment]
Snowball articles are showing up on the home page and under categories for me:

![screen shot 2016-08-26 at 5 22 13 pm](https://cloud.githubusercontent.com/assets/900407/18020909/058942f6-6bb2-11e6-9010-fa484f2e1daf.png)

![screen shot 2016-08-26 at 5 22 20 pm](https://cloud.githubusercontent.com/assets/900407/18020915/093e4a72-6bb2-11e6-882f-de16b9c189ec.png)

Can you post a screenshot of what you're seeing and what you want to happen?

**Comment by yerbol89** [comment]
Snowball articles not showing in Visual Compressor home page select category:

![image](https://cloud.githubusercontent.com/assets/993795/18202658/730b73d6-7133-11e6-8406-27447394e73b.png)

Default wordpress category page show normal:
https://szh.kz/category/suretter-soejlejdi

But home page i use Visual Composer plugin. And for select category page not howing Snow post.

![image](https://cloud.githubusercontent.com/assets/993795/18202774/199883d8-7134-11e6-8c86-bc2bae6a4747.png)

![image](https://cloud.githubusercontent.com/assets/993795/18202796/4958e61c-7134-11e6-8bbf-923ee994fccc.png)

![image](https://cloud.githubusercontent.com/assets/993795/18202840/8b0e9af2-7134-11e6-99fa-7f807a003cc1.png)

I select category. But my site home page not show Snowball post. Wordpress Default post show normal home page.

**Comment by yerbol89** [comment]
Please @thomaspark help me!

**Comment by thomaspark** [comment]
Unfortunately unable to debug this due to it being a paid theme I do not have access to.

It's possible you can write a custom function in `functions.php` that overrides the default behavior of the theme to include Snowball articles in the categories.
