### ISSUE TITLE
How to remove/change snowball permalink

### ISSUE THREAD

**Issue by francescogatto** [thomaspark/snowball#233]
Hi, I'm using your fantastic plugin! Hope you will continue the development 
How can I remove/change snowball permalink ? 

Thanks

**Comment by thomaspark** [comment]
Hey @Francescogatto, thanks!

[Simple Post Type Permalinks plugin](https://wordpress.org/plugins/simple-post-type-permalinks/) works great with Snowball for this purpose.

**Comment by francescogatto** [comment]
It works! Thanks so much
