### ISSUE TITLE
Newbie: Video block not available

### ISSUE THREAD

**Issue by ghost** [thomaspark/snowball#235]
I have started with snowball and I am unable to find the "video" block image in the snowball toolbar. There is youtube block, but if I wanted to add a auto-playing self-hosted video, how do I achieve the same?

![image](https://user-images.githubusercontent.com/1845880/42919199-6653316c-8b2e-11e8-85d4-7fa065fbee70.png)

**Comment by thomaspark** [comment]
Hi @jagan-veeraraghavan, Snowball doesn't offer a block for self-hosted videos, but you should be able to accomplish this using the HTML block. Roughly, for the HTML field:

```html
<video controls autoplay>
  <source src="../path/to/video.mp4" />
</video>
```

And for the CSS field:
```css
video {
  width: 100%;
  max-height: 100%;
}
```

**Comment by ghost** [comment]
Thanks @thomaspark . The snowball home page images showed a video button. That got me curious about the video feature. Your solution works perfectly for me

**Comment by thomaspark** [comment]
Glad you were able to get it working. I believe the YouTube block used to be called Video in earlier versions of Snowball, so that's what you're seeing on the homepage.
