### ISSUE TITLE
multiple unneeded POST calls

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#24]
happens not just in snowball post type, but posts and pages

![screen shot 2015-05-29 at 6 33 54 pm](https://cloud.githubusercontent.com/assets/900407/7893958/725fd26a-0631-11e5-819f-0a9820a645dd.png)

**Comment by brianlee389** [comment]
It is probably because I didn't check if it is the correct plugin that should be the function should be used on.

**Comment by thomaspark** [comment]
Apparently this is a general WordPress issue related to their Heartbeat API which is used for things like auto-saving: http://www.inmotionhosting.com/support/website/wordpress/heartbeat-ajax-php-usage
