### ISSUE TITLE
Database table existence

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#26]
The plugin doesn't check if your database table exists.
And if it doesn't exist, it should add a database table that is needed.
wp_snowball_articles and wp_snowball_blocks are the tables that need to be added.

**Comment by sukritchhabra** [comment]
Tables do not exist after Deactivation.
Tables do not exist after Activation.
Tables do not exist after Update Post. None of the changes made are saved.

[No Error messages displayed]

**Comment by thomaspark** [comment]
@sukritchhabra, @brianlee389, did we get this working on Windows?

**Comment by sukritchhabra** [comment]
![dberror](https://cloud.githubusercontent.com/assets/6703126/8884819/ea2d8018-3227-11e5-92af-d54e05ec54ad.png)
- Fixed by changing 

```
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8_unicode_ci');
```

to 

```
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');
```
