### ISSUE TITLE
Map branch - All known bugs

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#29]
Is not saving to Database. Clicking Update post doesn't save changes. (saving to DB on Brians build is working.)

Dashboard displays error on snowball.php. Same error is displayed when 'choose image' in the image module is clicked. The error doesn't hinder imgae functionality though. (screenshot attached)
![error](https://cloud.githubusercontent.com/assets/6703126/7919999/051632e0-086a-11e5-8e57-2ab672659876.png)

Once we enter the snowball menu, where all articles are being displayed, there is an illegal reference to snowball which is displayed as a console error.

Splash preview has a empty space below preview. (Is this intentional?)

**Comment by thomaspark** [comment]
You have multiple, unrelated bugs. You should open a separate issue for each bug, and copy & paste the error text if you get one (like dashboard error), or attach screenshot for visual bugs (like empty space below preview).

You should be seeing the same dashboard on the upstream/master branch, so it's not specific to map branch. They're related to #23, which we can fix by checking that we're on the edit page for snowball post type in the DB code.

If your block state isn't being saved, can you check that you have the two db tables created? If not, deactivating/reactivating the plugin might cause them to be created for you.

**Comment by thomaspark** [comment]
Another thing I forgot to mention. Don't clone my maps branch, which is already out of date, but just copy the `map` module directory from it into the latest upstream/master.

**Comment by sukritchhabra** [comment]
I tried deactivating and reactivating the plugin. that isn't working.

**Comment by thomaspark** [comment]
Can you open new issues for each of the bugs? Also, double-check that they don't already exist.

For the DB not being created, we have issue #26 open.

For data not being saved, include info about whether the tables exist in your DB, and copy & paste any error messages (not just screenshots) that you're getting.
