### ISSUE TITLE
Populating the admin blocks needs refactoring for Codemirror

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#53]
Codemirror can only retrieve <textarea>'s by their id to create the text editor. The code currently doesn't allow this now, but shouldn't be hard to add. Brian Lee would like to discuss the changes before making them.
So we need to dynamically generate the id's
http://stackoverflow.com/questions/9374894/can-codemirror-find-textareas-by-class"

**Comment by thomaspark** [comment]
According to the docs, you pass it the dom element (which can be selected any number of ways) instead of id. See https://codemirror.net/doc/manual.html#fromTextArea

You can also create the editor programmatically instead of from a textarea.

**Comment by brianlee389** [comment]
Classes work, finally figured it out.
