### ISSUE TITLE
new block for quote

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#59]

**Comment by sukritchhabra** [comment]
In the speech-bubble quote, do we allow the pointer to be in any direction or do we have a fixed no of directions we would allow

**Comment by thomaspark** [comment]
Let's go with only a single speech-bubble option, and have the arrow in the bottom left. Something like this shape:

![screen shot 2015-06-10 at 6 54 25 pm](https://cloud.githubusercontent.com/assets/900407/8096176/24ae2c86-0fa2-11e5-9fe3-f24074ec9908.png)

This link might be useful: http://joshnh.com/2011/10/18/how-to-make-a-speech-bubble-with-a-drop-shadow/

**Comment by sukritchhabra** [comment]
As of right now I've built it with options. So you could have a left/right/top/bottom and it looks a bit different than this. I'll remove the options tomorrow and change it to look closer to the pic above.

**Comment by thomaspark** [comment]
What does your speech bubble look like now? Mind posting a screenshot?

**Comment by sukritchhabra** [comment]
![quote1](https://cloud.githubusercontent.com/assets/6703126/8108711/1fcf5bd0-1020-11e5-9c21-cde30c9cddf5.png)

**Comment by sukritchhabra** [comment]
![quote2](https://cloud.githubusercontent.com/assets/6703126/8108718/28603652-1020-11e5-9a71-28eab2ff4e2a.png)

**Comment by sukritchhabra** [comment]
- There are some bugs. 
- Also the options are increasing the css size considerabily.

**Comment by thomaspark** [comment]
Thanks, it's getting there!

**Comment by sukritchhabra** [comment]
So do you want me to remove the options or keep them?

**Comment by thomaspark** [comment]
Remove, let's keep the speech bubble as a simple type option and avoid getting too complex with it.

**Comment by sukritchhabra** [comment]
Posting images of the new speech bubble below:

**Comment by sukritchhabra** [comment]
![quote1](https://cloud.githubusercontent.com/assets/6703126/8111650/f8cd4752-1030-11e5-874d-68bd18cb61d7.png)

**Comment by sukritchhabra** [comment]
![quote2](https://cloud.githubusercontent.com/assets/6703126/8111652/fd09ef0a-1030-11e5-919d-a851c6bd22cc.png)

**Comment by sukritchhabra** [comment]
- Width and height is better (fits text) than in the images above.
- Pointer has been moved to the left
- Just need your word on the background pointer position and dimensions Tom

**Comment by sukritchhabra** [comment]
Should the font of the citation be a little less than that of the quote in quote block?

**Comment by thomaspark** [comment]
Let's leave as is, and just wrap it in tags so the user can style it differently if they want.
