### ISSUE TITLE
create additional block types

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#6]
quote, image, gallery, map, comments, social media, navigation, section, etc...

**Comment by sukritchhabra** [comment]
map addded #6

**Comment by thomaspark** [comment]
Haven't received the pull request yet. Before you submit, could you make sure the coding style matches the project (i.e., `{ }` placement, use of `' '` in php and `" "` in js, whitespace, etc.)

**Comment by thomaspark** [comment]
data tables, charts and graphs
maybe integrate with google docs and use a library like [sheetsee.js](http://jlord.us/sheetsee.js/)

video
paste in url to YouTube, Vimeo...

**Comment by thomaspark** [comment]
map module added in #32
