### ISSUE TITLE
new block for data table

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#60]

**Comment by thomaspark** [comment]
Here's a nice example of a sortable table:
http://fivethirtyeight.com/features/there-are-922-unisex-names-in-america-is-yours-one-of-them/

**Comment by sukritchhabra** [comment]
I started playing with the data tables and the highcharts library and realized this. 

How do we want to obtain the data? Do I create a js input to upload a csv file or does that need to be done outside the module?

**Comment by thomaspark** [comment]
CSV upload could work. Two additional possibilities are to have a spreadsheet-like input where data can be entered directly within Snowball, or linking to a Google spreadsheet.

Some links:
- http://handsontable.com/
- http://jlord.us/sheetsee.js/
- http://chriszarate.github.io/sheetrock/

**Comment by thomaspark** [comment]
Also keep in mind that this issue is strictly for presenting data in tables. Graphs and visualizations will come later. So no need to dive into highcharts yet.

**Comment by sukritchhabra** [comment]
Do we need any options apart from the ones im Handsontable in the admin.html side?
