### ISSUE TITLE
The scoped jquery code has an error of undefined is not a function

### ISSUE THREAD

**Issue by brianlee389** [thomaspark/snowball#63]
So when a snowball article is clicked, this code has an error message saying undefined is not a function:
(function($) {

  $(document).ready(function() {
    $.scoped();
  });

})(jQuery);

**Comment by brianlee389** [comment]
My master branch is exactly(should be) the same as yours and I get this.

**Comment by thomaspark** [comment]
This was being called in each preview iframe through `snowball.js`, but the library was not being included. I'm removing `snowball.js` from previews since they don't need to be scoped.
