### ISSUE TITLE
Is there a particular way to add script to the template.html?

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#69]
- I'm trying to work on the table and as of right am passing a json of the input the user enters on the admin.html to the template .html. Im trying to work with the handsontable library. It works without a problem otherwise but when I try to add script to the template side it doesn't work.
- Code in WP:
  ![codeinwp](https://cloud.githubusercontent.com/assets/6703126/8168896/16d73046-1374-11e5-9104-f6a487062def.png)

*Error in WP: 
![codeerror](https://cloud.githubusercontent.com/assets/6703126/8168908/2e0149fa-1374-11e5-9a80-a66665c70aa9.png)
- I tried this exact code with the exception of importing the library in the index.html and writing the script in a js file and it worked just fine.

**Comment by sukritchhabra** [comment]
Again, I'm playing around with this so any code you see in the image is not the way it will be structured or named towards the end.

**Comment by thomaspark** [comment]
Is jQuery a dependency of handsonstable? If so, we want to make sure jQuery is loaded first. Right now, it's being loaded after the blocks in `snowball-template.php`, so we may need to move it into head.

Another issue is that we don't want to load handsontable each time a table block is used. So our script could check that handsontable is available and only load the library if it doesn't exist.

**Comment by sukritchhabra** [comment]
- Yes jQuery is a dependancy of handsontable.
- Also currently I am not saving data from the block, everytime i'm dynamically clicking on the chart button to create this block. even if jQuery is being loaded after the creataion of the blocks, that should work for this block since it is already loaded.
- I realize that we since template.html is in an iframe, it may not have access to the snowball admin page's jQuery load so I tried to manully load it in the template.html file also (before handsontable) and that didn't change anything.
- I will add a check for handsontable load to see if it has already been loaded.

**Comment by thomaspark** [comment]
`snowball-template.php` (which is used for both for both the preview iframe and the actual page) doesn't have access to the admin's jQuery, but loads jQuery itself.

**Comment by sukritchhabra** [comment]
- I'm assuming this is what you meant earlier was this so I moved it from before the end of body to before the end of `</head>` and this didn't work either. 

![tempcode](https://cloud.githubusercontent.com/assets/6703126/8171281/aebd9426-1384-11e5-8006-4c613a717409.png)
