### ISSUE TITLE
Navigating editor with arrow keys jumps/scrolls the editor to make the current cursor position the last line of the editor.

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#78]

**Comment by sukritchhabra** [comment]
- A similiar bug exists with `ctrl`+`shift`+`right/left arrow`
- After a selection it unselects everything that was selected.
- An unnecessary `->` or `<-` keypress after selection, might be the cause of this

**Comment by thomaspark** [comment]
I suggest that we set up separate handlers for the widgets and editors, and only call `refreshEditors` on changes to `.snowball-tinker`, not `.snowball-code`.

**Comment by brianlee389** [comment]
This issue would be solved if on("input"), is used instead of keydown. I don't get this problem when I do that

**Comment by thomaspark** [comment]
Ah right, forgot about the change to `input`. That works too!

**Comment by thomaspark** [comment]
Question: With the `on("input")` change, doesn't `refreshEditors` still get called when typing into the code editor? Is there any need to call `refreshEditors` in that situation?

**Comment by brianlee389** [comment]
Yes it does get called. It only needs to be called when regular input and textareas are used(non-codemirror textareas).
