### ISSUE TITLE
add code view

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#8]
expand block to allow inspection of html/css/js code responsible for block
as well as custom css/js to add additional style and behavior to block

**Comment by brianlee389** [comment]
Use code mirror.
Figure out how to use the option to make part of the code not editable and have language support for each respective language.
Only make it editable for javascript and css.

**Comment by thomaspark** [comment]
Mostly implemented in #73.

Just need to update HTML pane when widget values are changed.

**Comment by thomaspark** [comment]
Done.
