### ISSUE TITLE
Allowing document-wide properties

### ISSUE THREAD

**Issue by sukritchhabra** [thomaspark/snowball#93]
- If a user want to assign a CSS property to an elemnt on the whole web page he/she has to assign that property in each block.
- example: If I want to define a custom font, there is no place for me to define it for the whole page. I have to define it for each block I want to use this custom font in, which in my case then becomes every block.
- Should we provide a place where the user can add/remove CSS properties of the whole page?

**Comment by thomaspark** [comment]
See #206.
