### ISSUE TITLE
add soundcloud module

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#94]

**Comment by brianlee389** [comment]
Soundcloud doesn't have id the system youtube and/or vine has that makes it easy for you to just copy and paste the link.

For example,
the link to the song:
https://soundcloud.com/lolomusic/lolo-i-dont-wanna-have-to-lie
the embed link:
"https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/211069362&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"

Or we can use the soundcloud javascript api

**Comment by thomaspark** [comment]
Yeah, we'd probably have to dip into the [API](https://developers.soundcloud.com/docs/api/guide#resolving) to resolve ID <—> URL.
